#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2017.4 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Sun Jun 24 13:03:35 -03 2018
# SW Build 2086221 on Fri Dec 15 20:54:30 MST 2017
#
# Copyright 1986-2017 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
ExecStep()
{
"$@"
RETVAL=$?
if [ $RETVAL -ne 0 ]
then
exit $RETVAL
fi
}
ExecStep xelab -wto ec404b5e553c4131bfa7583debb2a600 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot FP_Mean_Cov_v1_0_S00_AXI_behav xil_defaultlib.FP_Mean_Cov_v1_0_S00_AXI -log elaborate.log
